### PR TITLE
Xiu yan

### PR DESCRIPTION
**Pull request by SongGdsk**
提交Xiu Yan图标

### CODE REVIEW

**Comment by crossle** [comment]
Why delete other assets?

**Comment by SongGdsk** [comment]
sorry，i am not good at this





------------------ Original ------------------

**Comment by SongGdsk** [comment]
> Why delete other assets?

should i try to be right again?

**Comment by SongGdsk** [comment]
> Why delete other assets?

因为不太会弄，我以为只需要提交我的就行了，所以把别的删了，我提交的内容正确吗，可以帮我提交上去吗，还是我要重新弄一下。

**Pull request closed without merging**
