### PR TITLE
SFC asset profile

### PR DESCRIPTION
**Pull request by yijunyu**
Set Flag Coin is a new asset based on Ether.

### CODE REVIEW

**Comment by jadeydi** [comment]
please don't use a white background,  icon example: https://mixin-images.zeromesh.net/UasWtBZO0TZyLTLCFQjvE_UYekjC7eHCuT_9_52ZpzmCC-X-NPioVegng7Hfx0XmIUavZgz5UL-HIgPCBECc-Ws

**Comment by yijunyu** [comment]
fixed the problem now with a gold background

**Comment by jadeydi** [comment]
Make sure the quality of your picture higher

**Comment by yijunyu** [comment]
Have improved the icon quality, thanks.

**Comment by crossle** [comment]
image
What's the logo border?

**Comment by yijunyu** [comment]
The border colour has been fixed now. Thank you.

**Pull request merged**
